name: Svelte Check & ESLint

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prettier:
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install
        run: npm ci

      - name: Run Svelte Check
        id: check
        run: npm run check
        continue-on-error: true

      - name: Run ESLint
        run: npm run lint

      - name: Fail if Svelte Check failed
        if: steps.check.outcome == 'failure'
        run: exit 1
