name: Prettier Code Formatting

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prettier:
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Prettify code
        uses: creyD/prettier_action@v4.6
        with:
          working_directory: ${{ env.FORGEJO_WORKSPACE }}
          prettier_options: --write .
          prettier_plugins: "prettier-plugin-svelte prettier-plugin-tailwindcss"
          allow_other_plugins: true
          commit_message: "style: Format code"
          git_identity: actions
